README.md
=> Add electron-forge-rspack-template

README.md
https://github.com/web-infra-dev/rspress/pull/447#issuecomment-1867152043
=> doc: add rspress translate plugin

README.md
Add rsbuild-plugin-console-debug
=> Add rsbuild-plugin-console-debug

README.md
https://github.com/hunghg255/rsbuild-plugin-react-inspector
=> Add rsbuild-plugin-react-inspector

README.md
- Update rsbuild plugin svelte inspector, vue inspector
=> doc: add plugin svelte inspector, vue inspector

README.md
https://github.com/sumy7/rsbuild-plugin-generate-file
=> Add rsbuild-plugin-generate-file

README.md
https://github.com/ulivz/rspress-plugin-remote-page
=> Add rspress-plugin-remote-page

README.md
https://rsbuild.dev/plugins/list/index
=> Add official Rsbuild plugins

README.md
https://rspress.dev/plugin/official-plugins/overview.html
=> Add official Rspress plugins

README.md
https://github.com/rspack-contrib/rspack-examples
=> Add rspack-examples

README.md
https://rsbuild.dev/plugins/list/plugin-eslint
=> Add @rsbuild/plugin-eslint

README.md
https://github.com/DMaiGit/rsbuild_vue3_h5_template
=> Add rsbuild_vue3_h5_template

README.md
[unplugin-auto-import](https://github.com/unplugin/unplugin-auto-import): Auto import APIs on-demand.
=> Add unplugin-auto-import

README.md
Hi, I add my plugin @aaroon/workbox-rspack-plugin. It is full featured and passes all the tests from `workbox-webpack-plugin`, and it should help rspack users.
=> Add @aaroon/workbox-rspack-plugin

README.md
https://github.com/filc-dev/rsbuild-chrome-extension-boilerplate-react
=> Add rsbuild-chrome-extension-boilerplate-react

README.md
https://github.com/rspack-contrib/rsbuild-plugin-google-analytics
=> Add rsbuild-plugin-google-analytics

README.md
https://github.com/filc-dev/rsbuild-plugin-web-extension
=> Add rsbuild-plugin-web-extension

README.md
https://github.com/rspack-contrib/rsbuild-plugin-open-graph
=> Add rsbuild-plugin-open-graph

README.md
repo: https://github.com/m1911star/rsbuild-plugin-posthog
npm: https://www.npmjs.com/package/rsbuild-plugin-posthog
=> Add rsbuild-plugin-posthog

README.md
https://github.com/rspack-contrib/rsfamily-desgin-resources
=> Add Rsfamily Design Resources

README.md
- [Repo](https://github.com/h7ml/shark) 
- [Preview](https://shark.h7ml.cn/)
=> docs: Rsbuild Starter added the Shark template.

README.md
https://rspress.dev/plugin/official-plugins/rss.html
=> Add @rspress/plugin-rss

README.md
https://rsbuild.dev/plugins/list/plugin-basic-ssl
=> Add @rsbuild/plugin-basic-ssl

README.md
https://github.com/rspack-contrib/rspack-manifest-plugin
=> Add rspack-manifest-plugin

README.md
More rspress community plugins!
=> docs(rspress): add rspress community plugins

README.md
From: https://www.rspack.dev/guide/compatibility/plugin
=> Add some webpack plugins

README.md
https://www.npmjs.com/package/@arco-plugins/unplugin-react
=> Add @arco-plugins/unplugin-react

README.md
https://github.com/tobua/inject-manifest-plugin
=> Add inject-manifest-plugin

README.md
https://github.com/tmkx/webx-kit
https://www.npmjs.com/package/@webx-kit/rsbuild-plugin
=> Add @webx-kit/rsbuild-plugin

README.md
https://github.com/jl917/rspress-plugin-clarity
=> Add rspress-plugin-clarity

README.md
=> Add @nx/rspack

README.md
https://github.com/SukkaW/react-compiler-webpack
=> Add react-compiler-webpack

README.md
Add some Rspack supported loaders
=> Add some Rspack supported loaders

README.md
https://github.com/jl917/rspress-plugin-sitemap
=> Add rspress-plugin-sitemap

README.md
https://rsbuild.dev/plugins/list/plugin-typed-css-modules
=> Add @rsbuild/plugin-typed-css-modules

README.md
https://www.npmjs.com/package/rspack-plugin-prefresh
=> Add rspack-plugin-prefresh

README.md
https://github.com/rspack-contrib/rspack-chain
=> Add rspack-chain

README.md
https://github.com/rspack-contrib/worker-rspack-loader
=> Add worker-rspack-loader

README.md
https://github.com/RyanProMax/electron-react-rspack
=> Add electron-react-rspack

README.md
https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing
https://www.npmjs.com/package/@tanstack/router-plugin
=> Add @tanstack/router-plugin

README.md
https://github.com/renzp94/unplugin-build-info
=> Add unplugin-build-info

README.md
add emp3.0 to ecosystem part, emp3.0 is a high-performance enterprise-level front-end build system built on the Rust ecosystem.
=> Add emp3.0

README.md
Optimize the naming of emp3.0, changing it to EMP 3.0.
=> Optimize the naming of EMP 3.0

README.md
https://github.com/zh-lx/code-inspector
=> Add code-inspector-plugin

README.md
Improve ecosystem, add description and move some projects.
=> Improve ecosystem

README.md
- [@rspack/plugin-react-refresh](https://www.rspack.dev/guide/tech/react#fast-refresh): Support React Fast Refresh.
- [@rspack/plugin-preact-refresh](https://www.rspack.dev/guide/tech/preact#preact-refresh): Support Preact Refresh.
=> Add @rspack/plugin-react-refresh

README.md
https://github.com/rsbuild-contrib/rsbuild-plugin-html-minifier-terser
=> Add rsbuild-plugin-html-minifier-terser

README.md
https://github.com/SyMind/rspackify
=> Add rspackify

README.md
https://github.com/serwist/serwist
https://serwist.pages.dev/docs/webpack-plugin
=> Add @serwist/webpack-plugin

README.md
https://github.com/alonronin/react-tailwind-rsbuild-boilerplate
=> Add react-tailwind-rsbuild-boilerplate

README.md
https://github.com/pengzhanbo/rspack-plugin-mock
=> Add rspack-plugin-mock

README.md
https://github.com/denniscual/spinpack
=> Add Spinpack

README.md
Add @rspack/lite-tapable and update some links.
=> Add @rspack/lite-tapable

README.md
=> Add community blogs

README.md
* add `aumi` in `Ecosystem`
* add `aumi-example` in `Rsbuild Starter`
=> docs: add aumi and starter

README.md
https://github.com/birchill/react-cosmos-plugin-rspack/
=> Add react-cosmos-plugin-rspack

README.md
Add dotenv-webpack and remove the deprecated rspack-plugin-dotenv
=> Add dotenv-webpack

README.md
https://github.com/vue-macros/vue-macros
=> Add unplugin-vue-macros

README.md
https://github.com/rspack-contrib/rspack-plugin-cli-copy
=> Add rspack-plugin-cli-copy

README.md
https://www.npmjs.com/package/rsbuild-plugin-dts
=> Add rsbuild-plugin-dts

README.md
https://github.com/rspack-contrib/rsbuild-plugin-ejs
=> Add rsbuild-plugin-ejs

README.md
- [2024-08] [开发体验的彻底提升，从 Vite 迁移到 Rspack](https://moonvy.com/blog/post/2024/migrate-vite-to-rsbuild/)
- [2024-08] [译：前 Firefox 工程师迁移到 Rspack 的经验教训](https://juejin.cn/post/7402554147276980224)
- [2024-07] [基于 Rspack 实现大仓应用构建提效实践](https://juejin.cn/post/7389925302020014118)
=> Add Chinese blogs

README.md
https://medium.com/@gfox1984/module-federation-users-now-have-a-clear-upgrade-path-1701de23f58e
=> Add a new blog

README.md
Hi, my plugin is now compatible with Rspack 1.0. Need to be use with HTMLWebpackPlugin or HTMLRspackPlugin.
https://github.com/Applelo/unplugin-inject-preload
=> Add unplugin-inject-preload

README.md
- [2024-09] [A bundler story: migrating from Webpack to Rspack](https://medium.com/alan/a-bundler-story-migrating-from-webpack-to-rspack-f548c62f757d)
=> A bundler story: migrating from Webpack to Rspack

README.md
https://github.com/edbzn/ng-rspack
=> Add ng-rspack

README.md
- [2024-08] [Optimizing SPA load times with async chunks preloading (use Rsbuild)](https://mmazzarolo.com/blog/2024-08-13-async-chunk-preloading-on-load/)
=> Add "Optimizing SPA load times with async chunks preloading"

README.md
support `rtlscss-webpack-plugin`
=> feat: add rtlcss-rspack-plugin

README.md
add [html-inline-css-rspack-plugin](https://github.com/cbbfcd/html-inline-css-rspack-plugin)
=> feat: add html-inline-css-rspack-plugin

README.md
add `html-rspack-skip-assets-plugin` 🎆🎆
=> add html-rspack-skip-assets-plugin

README.md
category rsbuild plugin, easy for users to view.
=> docs: category rsbuild plugins

README.md
- [2024-09] [我把大型团队项目从 Vite 前端迁移到了 Rsbuild，收益如何？](https://juejin.cn/post/7425804396292325414)
- [2024-09] [[译] 一个关于打包工具的故事：从 webpack 迁移到 Rspack](https://juejin.cn/post/7425598941859676170)
=> Add some Chinese blogs

README.md
- Rsbuild config monorepo  with Turborepo module federation
=> Add Rsbuild Starter

README.md
https://docusaurus.io/blog/releases/3.6
=> Add Docusaurus

README.md
automatically generate alias based on path
=> Add rsbuild-plugin-auto-alias

README.md
https://github.com/rspack-contrib/rsbuild-plugin-tailwindcss
=> Add rsbuild-plugin-tailwindcss

README.md
add plugins:
- [@electron-rsbuild/plugin-main](https://www.npmjs.com/package/@electron-rsbuild/plugin-main)
- [@electron-rsbuild/plugin-preload](https://www.npmjs.com/package/@electron-rsbuild/plugin-preload)
- [@electron-rsbuild/plugin-renderer](https://www.npmjs.com/package/@electron-rsbuild/plugin-renderer)
add electron build tools:
- [@electron-rsbuild/core](https://www.npmjs.com/package/@electron-rsbuild/core)
=> Add electron-rsbuild

README.md
https://github.com/module-federation/core/tree/main/packages/rsbuild-plugin
=> Add @module-federation/rsbuild-plugin

README.md
https://github.com/rspack-contrib/ts-checker-rspack-plugin
=> Add ts-checker-rspack-plugin

README.md
The Nx Plugin for Rsbuild contains an Nx plugin, executors and utilities that support building applications using Rsbuild.
https://nx.dev/nx-api/rsbuild
=> Add `@nx/rsbuild`

README.md
- [2025-01] [Nx and Angular with Rspack and Module Federation](https://www.angulararchitects.io/en/blog/nx-with-rspack-and-module-federation/)
=> Add new blog

README.md
https://edbzn.dev/state-of-rspack-in-angular/
=> Add "State of Rspack in Angular"

README.md
- [Re.Pack](https://github.com/callstack/repack): A toolkit to build your React Native application with Rspack.
=> Add Re.Pack

README.md
https://www.npmjs.com/package/rsbuild-plugin-aws-lambda
Feature request from: https://github.com/orgs/web-infra-dev/discussions/10
=> Add rsbuild-aws-lambda-plugin

README.md
https://github.com/xbzhang2020/rsbuild-plugin-web-ext/blob/main/packages/rsbuild
=> Add rsbuild-plugin-web-ext

README.md
- [@devjskit/rsbuild-plugin-langs](https://github.com/devjskit/rsbuild-plugin-langs): Extract content from JSON files and merge into a multi-language file.
=> Add @devjskit/rsbuild-plugin-langs

README.md
- [Rspeedy](https://lynxjs.org/rspeedy/): The Rspack-based build tool designed specifically for [Lynx](https://lynxjs.org/) applications.
=> Add Rspeedy

README.md
https://x.com/Michael_Hladky/status/1897430323295588364
=> Update link to Angular Rspack

README.md
- [@intlify/unplugin-vue-i18n](https://github.com/intlify/bundle-tools/tree/main/packages/unplugin-vue-i18n): unplugin for Vue I18n.
=> Add unplugin-vue-i18n

README.md
Add @seed-design/rsbuild-plugin
=> Add @seed-design/rsbuild-plugin

README.md
- [2025-03] [Using Rspack with Angular](https://nx.dev/blog/using-rspack-with-angular)
=> Add "Using Rspack with Angular"

README.md
https://github.com/tbocek/preveltekit
=> Add PrevelteKit

README.md
https://rspack.dev/guide/tech/next
=> Add next-rspack

README.md
https://github.com/web-infra-dev/rstest
=> Add Rstest

README.md
https://github.com/aliezzahn/rsbuild-plugin-markdown-loader
=> Update README.md - add rsbuild-plugin-markdown-loader plugin to loader list

README.md
add rsbuild-plugin-css-optimizer plugin
=> Add rsbuild-plugin-css-optimizer

README.md
update [rsbuild-plugin-css-optimizer](https://github.com/aliezzahn/rsbuild-plugin-css-optimizer) description
=> Update rsbuild-plugin-css-optimizer description

README.md
- [@mutsuntsai/rsbuild-plugin-vue-ssg](https://github.com/mutsuntsai/rsbuild-plugin-vue-ssg): Generate Vue SSG contents and inject those into HTML for Rsbuild.
=> Add rsbuild-plugin-vue-ssg

README.md
- [rsbuild-plugin-rempa](https://github.com/sumy7/rsbuild-plugin-rempa): A Rsbuild plugin designed to collect pages and generate a Multi-Page Application (MPA).
=> Add rsbuild-plugin-rempa

README.md
=> Add electron-react-rspack-boilerplate
